object frmDeliveries: TfrmDeliveries
  Left = 0
  Top = 0
  Caption = 'Deliveries'
  ClientHeight = 354
  ClientWidth = 378
  Color = clActiveCaption
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object lblMaxLoad: TLabel
    Left = 48
    Top = 19
    Width = 80
    Height = 15
    Caption = 'lblMaxLoad'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
  end
  object lblCargoType: TLabel
    Left = 223
    Top = 51
    Width = 8
    Height = 15
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -9
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
    WordWrap = True
  end
  object lblReward: TLabel
    Left = 223
    Top = 96
    Width = 8
    Height = 15
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -9
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
  end
  object lblTime: TLabel
    Left = 223
    Top = 125
    Width = 8
    Height = 15
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -9
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
  end
  object lblMass: TLabel
    Left = 223
    Top = 152
    Width = 8
    Height = 15
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -9
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
  end
  object lbxDeliveries: TListBox
    Left = 48
    Top = 40
    Width = 169
    Height = 265
    ItemHeight = 13
    TabOrder = 0
    OnClick = lbxDeliveriesClick
  end
  object btnDelivery: TButton
    Left = 120
    Top = 311
    Width = 121
    Height = 25
    Caption = 'Start Delivery'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    OnClick = btnDeliveryClick
  end
  object btnClose: TButton
    Left = 31
    Top = 311
    Width = 75
    Height = 25
    Caption = 'Close'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Fixedsys'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    OnClick = btnCloseClick
  end
end
